#!/bin/bash

echo "Cleaning..."
./cleanAll
echo "Done!"
echo "Compiling..."
export CLASSPATH=$PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin:.
javac -d bin/ src/**/*.java
echo "Done!"