#!/bin/bash

echo "Cleaning..."
./cleanAll
echo "Done!"
echo "Compiling..."
javac -cp $PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin:. -d bin/ src/**/*.java -Xlint:unchecked
echo "Done!"