#!/bin/bash
echo "Cleaning all..."
sh ./cleanAll
echo "Archiving..."
mkdir -p moodle
tar --exclude='genDeliverable' --exclude='moodle' --exclude='.git' -czf moodle/BELKHIR.ICARD.SIT213.EtapeX.tar.gz *
echo "Done!"