#!/bin/bash

export CLASSPATH=$PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin:.

java -cp bin/ simulateur.Simulateur -mess 101001101

java -cp bin/ simulateur.Simulateur -mess 12

java -cp bin/ simulateur.Simulateur -seed 1209

java -cp bin/ simulateur.Simulateur -mess 101001101

java -cp bin/ simulateur.Simulateur -mess 101001101 -form RZ

java -cp bin/ simulateur.Simulateur -mess 101001101 -form RZ -nbEch 10000

java -cp bin/ simulateur.Simulateur -mess 101001101 -form NRZ -ampl -1f 1f

java -cp bin/ simulateur.Simulateur -mess 101001101 -form NRZT -ampl -1f 1f

java -cp bin/ simulateur.Simulateur -mess 101001101 -form NRZT -ampl -1f 1f -nbEch 10000

java org.junit.runner.JUnitCore tests.AllTests
