#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
ITALICRED="\e[3;${RED}m"
ENDCOLOR="\e[0m"

./compile

java -cp $PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin/ org.junit.runner.JUnitCore tests.AllTests

if (( $? != 0 )); then
    echo -en "\n"
    echo -en "${RED}Junit tests failed${ENDCOLOR}"
    exit 1
else 
    echo -e "${GREEN}All JUnit tests passed${ENDCOLOR}\n"
fi

test_cases=(
    "-mess 101001101"
    "-mess 12"
    "-seed 1209"
    "-mess 101001101"
    "-mess 101001101 -form RZ"
    "-mess 101001101 -form RZ -nbEch 10000"
    "-mess 101001101 -form NRZ -ampl -1f 1f"
    "-mess 101001101 -form NRZT -ampl -1f 1f"
    "-mess 101001101 -form NRZT -ampl -1f 1f -nbEch 10000"
    "-mess 1000 -seed 1308 -form NRZ -ampl -1f 1f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -2f 1f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -4f 1f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -6f 1f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -8f 1f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -10f 1f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -10f 2f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -10f 4f -snrpb -3f"
    "-mess 1000 -seed 1308 -form NRZ -ampl -10f 6f -snrpb -3f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb -10f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb -5f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb -3f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 0f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 3f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 5f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 5f -nbEch 100"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 10f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 20f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 1f -snrpb 20f -nbEch 100"
    "-mess 1000 -form NRZT -ampl -1f 1f -snrpb -3f -nbEch 100"
    "-mess 1000 -form RZ -ampl -1f 1f -snrpb -3f -nbEch 100"
    "-mess 100 -seed 1308 -form NRZT -ampl -1f 0f -snrpb -10f"
    "-mess 100 -seed 1308 -form NRZT -ampl -1f 0f -snrpb -5f"
    "-mess 100 -seed 1308 -form NRZT -ampl -1f 0f -snrpb -3f"
    "-mess 100 -seed 1308 -form NRZT -ampl -1f 0f -snrpb 0f"
    "-mess 100 -seed 1308 -form NRZT -ampl -1f 0f -snrpb 3f"
    "-mess 100 -seed 1308 -form NRZT -ampl -1f 0f -snrpb 5f"
    "-mess 100 -seed 1308 -form RZ -ampl -1f 0f -snrpb -10f"
    "-mess 100 -seed 1308 -form RZ -ampl -1f 0f -snrpb -5f"
    "-mess 100 -seed 1308 -form RZ -ampl -1f 0f -snrpb -3f"
    "-mess 100 -seed 1308 -form RZ -ampl -1f 0f -snrpb 0f"
    "-mess 100 -seed 1308 -form RZ -ampl -1f 0f -snrpb 3f"
    "-mess 100 -seed 1308 -form RZ -ampl -1f 0f -snrpb 5f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 0f -snrpb -10f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 0f -snrpb -5f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 0f -snrpb -3f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 0f -snrpb 0f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 0f -snrpb 3f"
    "-mess 100 -seed 1308 -form NRZ -ampl -1f 0f -snrpb 5f"
    "-mess 100 -seed 1308 -form NRZT -snrpb -10f"
    "-mess 100 -seed 1308 -form NRZT -snrpb -5f"
    "-mess 100 -seed 1308 -form NRZT -snrpb -3f"
    "-mess 100 -seed 1308 -form NRZT -snrpb 0f"
    "-mess 100 -seed 1308 -form NRZT -snrpb 3f"
    "-mess 100 -seed 1308 -form NRZT -snrpb 5f"
    "-mess 100 -seed 1308 -form RZ -snrpb -10f"
    "-mess 100 -seed 1308 -form RZ -snrpb -5f"
    "-mess 100 -seed 1308 -form RZ -snrpb -3f"
    "-mess 100 -seed 1308 -form RZ -snrpb 0f"
    "-mess 100 -seed 1308 -form RZ -snrpb 3f"
    "-mess 100 -seed 1308 -form RZ -snrpb 5f"
    "-mess 100 -seed 1308 -form NRZ -snrpb -10f"
    "-mess 100 -seed 1308 -form NRZ -snrpb -5f"
    "-mess 100 -seed 1308 -form NRZ -snrpb -3f"
    "-mess 100 -seed 1308 -form NRZ -snrpb 0f"
    "-mess 100 -seed 1308 -form NRZ -snrpb 3f"
    "-mess 100 -seed 1308 -form NRZ -snrpb 5f"
    "-mess 100 -seed 1308 -form NRZ -snrpb 3f -nbEch 100"
    "-mess 100 -seed 1308 -form NRZ -snrpb 3f -nbEch 100 -ti 20 0.4"
    "-mess 100 -seed 1308 -form NRZ -snrpb 5f -nbEch 100"
    "-mess 100 -seed 1308 -form NRZ -snrpb 5f -nbEch 100 -ti 20 0.4"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -ti 20 0.4 -s"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -ti 20 0.4 30 0.3 -s"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -ti 20 0.4 30 0.3 40 0.2 -s"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -ti 20 0.4 30 0.3 40 0.2 50 0.1 -s"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -ti 20 0.4 30 0.3 40 0.2 50 0.1 60 0.05 -s"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -snrpb 3f -ti 20 0.4 -s"
    "-mess 10 -seed 1308 -form NRZT -nbEch 100 -snrpb 30f -ti 20 0.4 -s"
)
cpt=0
for cmd in "${test_cases[@]}"; do
    ./simulateur $cmd
    if (( $? != 0 )); then
        echo -e "${RED}Test failed:${ENDCOLOR} ${ITALICRED} $cmd ${ENDCOLOR}"
        ((cpt++))
    fi
done
if (( $cpt != 0 )); then
    echo -en "\n"
    echo -en "${RED}$cpt tests failed${ENDCOLOR}"
    exit 1
fi

echo -e "${GREEN}All tests passed${ENDCOLOR}\n"
