#!/bin/bash

export CLASSPATH=$PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin:.

./simulateur -mess 101001101

./simulateur -mess 12

./simulateur -seed 1209

./simulateur -mess 101001101

./simulateur -mess 101001101 -form RZ

./simulateur -mess 101001101 -form RZ -nbEch 10000

./simulateur -mess 101001101 -form NRZ -ampl -1f 1f

./simulateur -mess 101001101 -form NRZT -ampl -1f 1f

./simulateur -mess 101001101 -form NRZT -ampl -1f 1f -nbEch 10000

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb -10f

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb -5f

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb -3f

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 0f

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 3f

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 5f

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 5f -nbEch 100 

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 10f 

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 20f 

./simulateur -mess 100 -form NRZ -ampl -1f 1f -snrpb 20f -nbEch 100 


java org.junit.runner.JUnitCore tests.AllTests
