name: '[Java] Génération des graphes'

on:
  push:
    branches: [ "graphs" ]

jobs:
  generate_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Java project
        uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: oracle
      - name: Build with script
        id: build
        run: ./compile
      - name: Exec with script
        id: exec
        if: steps.build.outputs.exit_code == 0
        run: /bin/sh ./genGraphs
      - name: Upload artifact
        if: steps.exec.outputs.exit_code == 0
        uses: actions/upload-artifact@v3
        with:
          path: ./*.csv
