name: Génération du livrable et du rapport

on:
  release:
    types: [created]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        id: compile
        uses: dante-ev/latex-action@latest
        with:
          working_directory: livrable
          root_file: main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: steps.compile.outputs.exit_code == 0
        with:
          name: B1.Belkhir.Icard.Fuchs.Alegre.Achille.rapport.etapeX.pdf
          path: livrable/main.pdf    
  livrable:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Generate livrable
        run: ./genDeliverable
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: B1.Belkhir.Icard.Fuchs.Alegre.Achille.logiciel.etapeX.tar.gz
          path: livrable/B1.Belkhir.Icard.Fuchs.Alegre.Achille.logiciel.etapeX.tar.gz
  test_du_livrable:
    runs-on: ubuntu-latest
    needs: livrable
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: B1.Belkhir.Icard.Fuchs.Alegre.Achille.logiciel.etapeX.tar.gz
          path: livrable
      - name: Test livrable
        run: chmod u+x ./Deploiement && ./Deploiement livrable/B1.Belkhir.Icard.Fuchs.Alegre.Achille.logiciel.etapeX