name: '[Bash] Test du livrable (logiciel uniquement)'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test_du_livrable:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Generate livrable
        run: ./genDeliverable
      - name: Test livrable
        run: ./Deploiement B1.Belkhir.Icard.Fuchs.Alegre.Achille.logiciel.etapeX
      